### PR TITLE
checks current guard and adds it to the auth()

### PR DESCRIPTION
**Pull request by eelco2k**
code changes for issue:

https://github.com/kenepa/resource-lock/issues/25

### CODE REVIEW

**Comment by Jehizkia** [comment]
Hey, thank you. Unfortunately, I'm getting an error when running your changes in a Filament demo project.

`App\Models\Shop\Product::getCurrentAuthGuardName(): Return value must be of type ?array, string returned`

**Comment by eelco2k** [comment]
I think the return type array|null is faulty and should be string|null

cause you can only have one current Active guard. Sorry for the bug

**Comment by eelco2k** [comment]
`     * @return string|null
     */
    private function getCurrentAuthGuardName(): string|null`

**Comment by Jehizkia** [comment]
Do you set the guard on the filament panel like so in your project:
https://filamentphp.com/docs/3.x/panels/users#setting-the-authentication-guard

**Comment by eelco2k** [comment]
Yes and in config/auth.php

but one panel i use for example the “web” guard but for another filament panel i use the “admin” guard. Both which are defined in config/auth.php

**Comment by Jehizkia** [comment]
I modified the `getCurrentAuthGuardName()` logic to depend on the filament facade for fetching the currently active guard.

**Comment by Jehizkia** [comment]
Thank you @eelco2k

**Pull request merged**
